// Code generated by "stringer -type opState"; DO NOT EDIT.

package muSupervisor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PENDING-0]
	_ = x[ACTIVE-1]
	_ = x[DONE-2]
}

const _opState_name = "PENDINGACTIVEDONE"

var _opState_index = [...]uint8{0, 7, 13, 17}

func (i opState) String() string {
	if i < 0 || i >= opState(len(_opState_index)-1) {
		return "opState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opState_name[_opState_index[i]:_opState_index[i+1]]
}
